af:
  - nl
an:
  - ca
  - es
ast:
  - es
be:
  - ru
bg:
  - mk
br:
  - fr
ca:
  - an
  - en
  - eo
  - es
  - fr
  - oc
  - pt
  - simple
  - sc
da:
  - nb
  - nn
  - sv
en:
  - ca
  - eo
  - es
  - sh
es:
  - an
  - ast
  - ca
  - en
  - eo
  - fr
  - gl
  - it
  - pt
  - simple
eu:
  - es
fr:
  - ca
  - eo
  - es
  - frp
  - oc
frp:
  - fr
gl:
  - es
  - pt
hi:
  - ur
id:
  - ms
is:
  - sv
it:
  - ca
  - es
  - sc
mk:
  - bg
  - en
  - sr
ms:
  - id
nb:
  - da
  - nn
  - sv
nl:
  - af
nn:
  - da
  - nb
  - sv
oc:
  - ca
pt:
  - ca
  - es
  - gl
pl:
  - szl
ru:
  - be
sh:
  - en
  - simple
  - sl
simple:
  - ca
  - es
  - sh
sl:
  - sh
  - sr
sv:
  - da
  - is
  - nb
  - nn
szl:
  - pl
ur:
  - hi
