handler: transform.js
languages:
  - af
  - am
  - ar
  - arz
  - as
  - ay
  - az
  - be
  - be-tarask
  - bg
  - bho
  - bm
  - bn
  - bs
  - ca
  - ceb
  - ckb
  - co
  - cs
  - cy
  - da
  - de
  - dv
  - ee
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fa
  - fi
  - fr
  - fy
  - ga
  - gan
  - gd
  - gl
  - gn
  - gom
  - gu
  - ha
  - haw
  - he
  - hi
  - hr
  - ht
  - hu
  - hy
  - id
  - ig
  - ilo
  - is
  - it
  - ja
  - jv
  - ka
  - kk
  - km
  - kn
  - ko
  - ku
  - ky
  - la
  - lb
  - lg
  - ln
  - lo
  - lt
  - lv
  - mai
  - mg
  - mi
  - mk
  - ml
  - mn
  - mni
  - mr
  - ms
  - mt
  - my
  - ne
  - nl
  - no
  - nso
  - ny
  - om
  - or
  - pa
  - pl
  - ps
  - pt
  - qu
  - ro
  - ru
  - rw
  - sa
  - sd
  - sh
  - si
  - simple
  - sk
  - sl
  - sm
  - sn
  - so
  - sq
  - sr
  - st
  - su
  - sv
  - sw
  - ta
  - te
  - tg
  - th
  - ti
  - tk
  - tl
  - tr
  - ts
  - tt
  - tw
  - ug
  - uk
  - ur
  - uz
  - vi
  - wuu
  - xh
  - yi
  - yo
  - yue
  - zh
  - zu
