af-nl: Apertium
ar-mt: Apertium
be-ru: Apertium
bg-mk: Apertium
ca-fr: Apertium
ca-oc: Apertium
ca-pt: Apertium
ca-sc: Apertium
en-gl: Apertium
es-ca: Apertium
es-fr: Apertium
es-gl: Apertium
es-it: Apertium
es-pt: Apertium
fr-oc: Apertium
gl-pt: Apertium
hi-ur: Apertium
id-ms: Apertium
is-sv: Apertium
it-sc: Apertium
kk-tt: Apertium
mk-bg: Apertium
mk-sr: Apertium
ms-id: Apertium
mt-ar: Apertium
nl-af: Apertium
pt-ca: Apertium
sh-sl: Apertium
sl-sr: Apertium
sv-da: Apertium
sv-is: Apertium
tt-kk: Apertium
ur-hi: Apertium
ca-eu: Elia
en-eu: Elia
es-eu: Elia
fr-eu: Elia
gl-eu: Elia
en-ig: Flores
en-is: Flores
en-oc: Flores
en-zu: Google
an-es: Google
af-zh: Google
ar-zh: Google
ast-es: Google
az-zh: Google
be-tarask-zh: Google
be-zh: Google
bg-zh: Google
bn-zh: Google
bs-zh: Google
ca-es: Google
ca-gl: Google
ca-simple: Google
ca-zh: Google
ceb-zh: Google
co-zh: Google
cs-zh: Google
cy-zh: Google
da-zh: Google
de-zh: Google
el-zh: Google
en-ca: Google
en-es: Google
en-fr: Google
en-ha: Google
en-it: Google
en-sh: Google
en-zh: Google
eo-zh: Google
es-ha: Google
es-simple: Google
es-zh: Google
et-zh: Google
eu-ca: Google
eu-es: Google
eu-fr: Google
eu-gl: Google
eu-simple: Google
eu-zh: Google
fa-zh: Google
fi-zh: Google
fr-ca: Google
fr-es: Google
fr-gl: Google
fr-ha: Google
fr-simple: Google
fr-zh: Google
fy-zh: Google
ga-zh: Google
gl-ca: Google
gl-es: Google
gl-fr: Google
gl-simple: Google
gl-zh: Google
gu-zh: Google
haw-zh: Google
ha-zh: Google
he-zh: Google
hi-zh: Google
hr-zh: Google
ht-zh: Google
hu-zh: Google
hy-zh: Google
id-zh: Google
ig-zh: Google
is-zh: Google
it-ca: Google
it-es: Google
it-zh: Google
ja-zh: Google
jv-zh: Google
ka-zh: Google
kk-zh: Google
km-zh: Google
kn-zh: Google
ko-zh: Google
ku-zh: Google
la-zh: Google
lo-zh: Google
lt-zh: Google
lv-zh: Google
mg-zh: Google
mi-zh: Google
mk-zh: Google
ml-zh: Google
mn-zh: Google
mr-zh: Google
ms-zh: Google
mt-zh: Google
my-zh: Google
ne-zh: Google
nl-zh: Google
no-zh: Google
ny-zh: Google
oc-es: Google
pa-zh: Google
pl-zh: Google
ps-zh: Google
pt-es: Google
pt-gl: Google
pt-zh: Google
ro-es: Google
ro-zh: Google
ru-uk: Google
ru-zh: Google
sd-zh: Google
simple-ca: Google
simple-es: Google
simple-eu: Google
simple-fr: Google
simple-gl: Google
simple-zh: Google
si-zh: Google
sk-zh: Google
sl-zh: Google
sm-zh: Google
sn-zh: Google
so-zh: Google
sq-zh: Google
sr-zh: Google
st-zh: Google
su-zh: Google
sv-zh: Google
sw-zh: Google
ta-zh: Google
te-zh: Google
tg-zh: Google
th-zh: Google
tl-zh: Google
tr-zh: Google
uk-zh: Google
ur-zh: Google
uz-zh: Google
vi-zh: Google
yi-zh: Google
yo-zh: Google
zu-zh: Google
en-ba: Yandex
fr-ba: Yandex
es-ba: Yandex
ru-ba: Yandex
ru-be: Yandex
en-ckb: Google
es-ckb: Google
fr-ckb: Google
simple-ckb: Google
