# source-mt : Source text as default MT option.
'en-am': source-mt
'az-ar': source-mt
'fa-ar': source-mt
'fr-ar': source-mt
'de-ar': source-mt
'en-ar': source-mt
'es-ar': source-mt
'he-ar': source-mt
'ko-ar': source-mt
'pt-ar': source-mt
'ru-ar': source-mt
'sv-ar': source-mt
'th-ar': source-mt
'tr-ar': source-mt
'af-az': source-mt
'am-az': source-mt
'ar-az': source-mt
'ba-az': source-mt
'be-az': source-mt
'be-tarask-az': source-mt
'bn-az': source-mt
'bg-az': source-mt
'bs-az': source-mt
'ca-az': source-mt
'cs-az': source-mt
'cy-az': source-mt
'da-az': source-mt
'el-az': source-mt
'en-az': source-mt
'eo-az': source-mt
'es-az': source-mt
'et-az': source-mt
'eu-az': source-mt
'fa-az': source-mt
'fi-az': source-mt
'fr-az': source-mt
'ga-az': source-mt
'gd-az': source-mt
'gl-az': source-mt
'gu-az': source-mt
'he-az': source-mt
'hi-az': source-mt
'hr-az': source-mt
'ht-az': source-mt
'hu-az': source-mt
'hy-az': source-mt
'id-az': source-mt
'is-az': source-mt
'ja-az': source-mt
'jv-az': source-mt
'ka-az': source-mt
'kk-az': source-mt
'kn-az': source-mt
'ko-az': source-mt
'ky-az': source-mt
'la-az': source-mt
'lt-az': source-mt
'lv-az': source-mt
'mg-az': source-mt
'mi-az': source-mt
'mhr-az': source-mt
'ml-az': source-mt
'mk-az': source-mt
'mn-az': source-mt
'mr-az': source-mt
'mrj-az': source-mt
'ms-az': source-mt
'mt-az': source-mt
'nb-az': source-mt
'ne-az': source-mt
'pa-az': source-mt
'pl-az': source-mt
'pt-az': source-mt
'ro-az': source-mt
'ru-az': source-mt
'si-az': source-mt
'sk-az': source-mt
'sl-az': source-mt
'sq-az': source-mt
'sr-az': source-mt
'su-az': source-mt
'sv-az': source-mt
'sw-az': source-mt
'ta-az': source-mt
'te-az': source-mt
'tg-az': source-mt
'th-az': source-mt
'tl-az': source-mt
'tr-az': source-mt
'tt-az': source-mt
'udm-az': source-mt
'uk-az': source-mt
'ur-az': source-mt
'uz-az': source-mt
'vi-az': source-mt
'xh-az': source-mt
'yi-az': source-mt
'zh-az': source-mt
'en-bn': source-mt
'eu-bn': source-mt
'af-ceb': source-mt
'am-ceb': source-mt
'ar-ceb': source-mt
'ba-ceb': source-mt
'be-ceb': source-mt
'bn-ceb': source-mt
'bg-ceb': source-mt
'bs-ceb': source-mt
'ca-ceb': source-mt
'cs-ceb': source-mt
'cy-ceb': source-mt
'da-ceb': source-mt
'el-ceb': source-mt
'en-ceb': source-mt
'id-ceb': source-mt
'ru-ceb': source-mt
'sv-ceb': source-mt
'th-ceb': source-mt
'tl-ceb': source-mt
'vi-ceb': source-mt
'zh-ceb': source-mt
'en-cy': source-mt
'es-cy': source-mt
'nl-cy': source-mt
'en-eo': source-mt
'es-eo': source-mt
'nl-eo': source-mt
'en-gu': source-mt
'fr-gu': source-mt
'he-gu': source-mt
'hi-gu': source-mt
'pt-gu': source-mt
'af-km': source-mt
'am-km': source-mt
'ar-km': source-mt
'az-km': source-mt
'ba-km': source-mt
'be-km': source-mt
'bn-km': source-mt
'bg-km': source-mt
'bs-km': source-mt
'ca-km': source-mt
'ceb-km': source-mt
'cs-km': source-mt
'cy-km': source-mt
'da-km': source-mt
'el-km': source-mt
'en-km': source-mt
'eo-km': source-mt
'es-km': source-mt
'et-km': source-mt
'eu-km': source-mt
'fa-km': source-mt
'fi-km': source-mt
'fr-km': source-mt
'ga-km': source-mt
'gd-km': source-mt
'gl-km': source-mt
'gu-km': source-mt
'he-km': source-mt
'hi-km': source-mt
'hr-km': source-mt
'ht-km': source-mt
'hu-km': source-mt
'hy-km': source-mt
'id-km': source-mt
'is-km': source-mt
'ja-km': source-mt
'jv-km': source-mt
'ka-km': source-mt
'kk-km': source-mt
'kn-km': source-mt
'ko-km': source-mt
'ky-km': source-mt
'la-km': source-mt
'lb-km': source-mt
'lo-km': source-mt
'lt-km': source-mt
'lv-km': source-mt
'mi-km': source-mt
'mg-km': source-mt
'mhr-km': source-mt
'ml-km': source-mt
'mk-km': source-mt
'mn-km': source-mt
'mrj-km': source-mt
'mr-km': source-mt
'ms-km': source-mt
'my-km': source-mt
'nb-km': source-mt
'ne-km': source-mt
'pa-km': source-mt
'pap-km': source-mt
'pl-km': source-mt
'pt-km': source-mt
'ro-km': source-mt
'ru-km': source-mt
'si-km': source-mt
'sk-km': source-mt
'sl-km': source-mt
'sq-km': source-mt
'sr-km': source-mt
'su-km': source-mt
'sv-km': source-mt
'sw-km': source-mt
'ta-km': source-mt
'te-km': source-mt
'tg-km': source-mt
'th-km': source-mt
'tl-km': source-mt
'tr-km': source-mt
'tt-km': source-mt
'udm-km': source-mt
'uk-km': source-mt
'ur-km': source-mt
'uz-km': source-mt
'vi-km': source-mt
'xh-km': source-mt
'yi-km': source-mt
'zh-km': source-mt
'en-kn': source-mt
'fr-kn': source-mt
'cs-la': source-mt
'de-la': source-mt
'en-la': source-mt
'es-la': source-mt
'fr-la': source-mt
'he-la': source-mt
'hu-la': source-mt
'it-la': source-mt
'de-lb': source-mt
'af-lo': source-mt
'am-lo': source-mt
'ar-lo': source-mt
'az-lo': source-mt
'ba-lo': source-mt
'be-lo': source-mt
'bn-lo': source-mt
'bg-lo': source-mt
'bs-lo': source-mt
'ca-lo': source-mt
'ceb-lo': source-mt
'cs-lo': source-mt
'cy-lo': source-mt
'da-lo': source-mt
'el-lo': source-mt
'en-lo': source-mt
'eo-lo': source-mt
'es-lo': source-mt
'et-lo': source-mt
'eu-lo': source-mt
'fa-lo': source-mt
'fi-lo': source-mt
'fr-lo': source-mt
'ga-lo': source-mt
'gd-lo': source-mt
'gl-lo': source-mt
'gu-lo': source-mt
'he-lo': source-mt
'hi-lo': source-mt
'hr-lo': source-mt
'ht-lo': source-mt
'hu-lo': source-mt
'hy-lo': source-mt
'id-lo': source-mt
'is-lo': source-mt
'ja-lo': source-mt
'jv-lo': source-mt
'ka-lo': source-mt
'kk-lo': source-mt
'km-lo': source-mt
'kn-lo': source-mt
'ko-lo': source-mt
'ky-lo': source-mt
'la-lo': source-mt
'lb-lo': source-mt
'lt-lo': source-mt
'lv-lo': source-mt
'mi-lo': source-mt
'mg-lo': source-mt
'mhr-lo': source-mt
'ml-lo': source-mt
'mk-lo': source-mt
'mn-lo': source-mt
'mrj-lo': source-mt
'mr-lo': source-mt
'ms-lo': source-mt
'my-lo': source-mt
'nb-lo': source-mt
'ne-lo': source-mt
'pa-lo': source-mt
'pap-lo': source-mt
'pl-lo': source-mt
'pt-lo': source-mt
'ro-lo': source-mt
'ru-lo': source-mt
'si-lo': source-mt
'sk-lo': source-mt
'sl-lo': source-mt
'sq-lo': source-mt
'sr-lo': source-mt
'su-lo': source-mt
'sv-lo': source-mt
'sw-lo': source-mt
'ta-lo': source-mt
'te-lo': source-mt
'tg-lo': source-mt
'th-lo': source-mt
'tl-lo': source-mt
'tr-lo': source-mt
'tt-lo': source-mt
'udm-lo': source-mt
'uk-lo': source-mt
'ur-lo': source-mt
'uz-lo': source-mt
'vi-lo': source-mt
'xh-lo': source-mt
'yi-lo': source-mt
'zh-lo': source-mt
'el-mhr': source-mt
'af-ml': source-mt
'am-ml': source-mt
'ar-ml': source-mt
'ba-ml': source-mt
'be-ml': source-mt
'bn-ml': source-mt
'bg-ml': source-mt
'bs-ml': source-mt
'ca-ml': source-mt
'ceb-ml': source-mt
'cs-ml': source-mt
'cy-ml': source-mt
'da-ml': source-mt
'el-ml': source-mt
'en-ml': source-mt
'eo-ml': source-mt
'es-ml': source-mt
'et-ml': source-mt
'eu-ml': source-mt
'fa-ml': source-mt
'fi-ml': source-mt
'fr-ml': source-mt
'ga-ml': source-mt
'gd-ml': source-mt
'gl-ml': source-mt
'gu-ml': source-mt
'he-ml': source-mt
'hi-ml': source-mt
'hr-ml': source-mt
'ht-ml': source-mt
'hu-ml': source-mt
'hy-ml': source-mt
'id-ml': source-mt
'is-ml': source-mt
'ja-ml': source-mt
'ka-ml': source-mt
'kk-ml': source-mt
'kn-ml': source-mt
'ko-ml': source-mt
'ky-ml': source-mt
'la-ml': source-mt
'lt-ml': source-mt
'lv-ml': source-mt
'mg-ml': source-mt
'mi-ml': source-mt
'mhr-ml': source-mt
'mk-ml': source-mt
'mn-ml': source-mt
'mrj-ml': source-mt
'mr-ml': source-mt
'ms-ml': source-mt
'mt-ml': source-mt
'nb-ml': source-mt
'ne-ml': source-mt
'pa-ml': source-mt
'pl-ml': source-mt
'pt-ml': source-mt
'ro-ml': source-mt
'ru-ml': source-mt
'si-ml': source-mt
'sk-ml': source-mt
'sl-ml': source-mt
'sq-ml': source-mt
'sr-ml': source-mt
'su-ml': source-mt
'sv-ml': source-mt
'sw-ml': source-mt
'ta-ml': source-mt
'te-ml': source-mt
'tg-ml': source-mt
'th-ml': source-mt
'tl-ml': source-mt
'tr-ml': source-mt
'tt-ml': source-mt
'udm-ml': source-mt
'uk-ml': source-mt
'ur-ml': source-mt
'uz-ml': source-mt
'vi-ml': source-mt
'xh-ml': source-mt
'yi-ml': source-mt
'zh-ml': source-mt
'af-mr': source-mt
'am-mr': source-mt
'ar-mr': source-mt
'ba-mr': source-mt
'be-mr': source-mt
'bn-mr': source-mt
'bg-mr': source-mt
'bs-mr': source-mt
'ca-mr': source-mt
'ceb-mr': source-mt
'cs-mr': source-mt
'cy-mr': source-mt
'da-mr': source-mt
'el-mr': source-mt
'en-mr': source-mt
'eo-mr': source-mt
'es-mr': source-mt
'et-mr': source-mt
'eu-mr': source-mt
'fa-mr': source-mt
'fi-mr': source-mt
'fr-mr': source-mt
'ga-mr': source-mt
'gd-mr': source-mt
'gl-mr': source-mt
'gu-mr': source-mt
'he-mr': source-mt
'hi-mr': source-mt
'hr-mr': source-mt
'ht-mr': source-mt
'hu-mr': source-mt
'hy-mr': source-mt
'id-mr': source-mt
'is-mr': source-mt
'ja-mr': source-mt
'ka-mr': source-mt
'kk-mr': source-mt
'kn-mr': source-mt
'ko-mr': source-mt
'ky-mr': source-mt
'la-mr': source-mt
'lt-mr': source-mt
'lv-mr': source-mt
'mg-mr': source-mt
'mi-mr': source-mt
'mhr-mr': source-mt
'mk-mr': source-mt
'ml-mr': source-mt
'mn-mr': source-mt
'mrj-mr': source-mt
'ms-mr': source-mt
'mt-mr': source-mt
'nb-mr': source-mt
'ne-mr': source-mt
'pa-mr': source-mt
'pl-mr': source-mt
'pt-mr': source-mt
'ro-mr': source-mt
'ru-mr': source-mt
'si-mr': source-mt
'sk-mr': source-mt
'sl-mr': source-mt
'sq-mr': source-mt
'sr-mr': source-mt
'su-mr': source-mt
'sv-mr': source-mt
'sw-mr': source-mt
'ta-mr': source-mt
'te-mr': source-mt
'tg-mr': source-mt
'th-mr': source-mt
'tl-mr': source-mt
'tr-mr': source-mt
'tt-mr': source-mt
'udm-mr': source-mt
'uk-mr': source-mt
'ur-mr': source-mt
'uz-mr': source-mt
'vi-mr': source-mt
'xh-mr': source-mt
'yi-mr': source-mt
'zh-mr': source-mt
'af-my': source-mt
'am-my': source-mt
'ar-my': source-mt
'az-my': source-mt
'ba-my': source-mt
'be-my': source-mt
'bn-my': source-mt
'bg-my': source-mt
'bs-my': source-mt
'ca-my': source-mt
'ceb-my': source-mt
'cs-my': source-mt
'cy-my': source-mt
'da-my': source-mt
'el-my': source-mt
'en-my': source-mt
'eo-my': source-mt
'es-my': source-mt
'et-my': source-mt
'eu-my': source-mt
'fa-my': source-mt
'fi-my': source-mt
'fr-my': source-mt
'ga-my': source-mt
'gd-my': source-mt
'gl-my': source-mt
'gu-my': source-mt
'he-my': source-mt
'hi-my': source-mt
'hr-my': source-mt
'ht-my': source-mt
'hu-my': source-mt
'hy-my': source-mt
'id-my': source-mt
'is-my': source-mt
'ja-my': source-mt
'jv-my': source-mt
'ka-my': source-mt
'kk-my': source-mt
'km-my': source-mt
'kn-my': source-mt
'ko-my': source-mt
'ky-my': source-mt
'la-my': source-mt
'lb-my': source-mt
'lo-my': source-mt
'lt-my': source-mt
'lv-my': source-mt
'mi-my': source-mt
'mg-my': source-mt
'mhr-my': source-mt
'ml-my': source-mt
'mk-my': source-mt
'mn-my': source-mt
'mrj-my': source-mt
'mr-my': source-mt
'ms-my': source-mt
'nb-my': source-mt
'ne-my': source-mt
'pa-my': source-mt
'pap-my': source-mt
'pl-my': source-mt
'pt-my': source-mt
'ro-my': source-mt
'ru-my': source-mt
'si-my': source-mt
'sk-my': source-mt
'sl-my': source-mt
'sq-my': source-mt
'sr-my': source-mt
'su-my': source-mt
'sv-my': source-mt
'sw-my': source-mt
'ta-my': source-mt
'te-my': source-mt
'tg-my': source-mt
'th-my': source-mt
'tl-my': source-mt
'tr-my': source-mt
'tt-my': source-mt
'udm-my': source-mt
'uk-my': source-mt
'ur-my': source-mt
'uz-my': source-mt
'vi-my': source-mt
'xh-my': source-mt
'yi-my': source-mt
'zh-my': source-mt
'af-ne': source-mt
'am-ne': source-mt
'ar-ne': source-mt
'ba-ne': source-mt
'be-ne': source-mt
'bn-ne': source-mt
'bg-ne': source-mt
'bs-ne': source-mt
'ca-ne': source-mt
'ceb-ne': source-mt
'cs-ne': source-mt
'cy-ne': source-mt
'da-ne': source-mt
'el-ne': source-mt
'en-ne': source-mt
'eo-ne': source-mt
'es-ne': source-mt
'et-ne': source-mt
'eu-ne': source-mt
'fa-ne': source-mt
'fi-ne': source-mt
'fr-ne': source-mt
'ga-ne': source-mt
'gd-ne': source-mt
'gl-ne': source-mt
'gu-ne': source-mt
'he-ne': source-mt
'hi-ne': source-mt
'hr-ne': source-mt
'ht-ne': source-mt
'hu-ne': source-mt
'hy-ne': source-mt
'id-ne': source-mt
'is-ne': source-mt
'ja-ne': source-mt
'ka-ne': source-mt
'kk-ne': source-mt
'kn-ne': source-mt
'ko-ne': source-mt
'ky-ne': source-mt
'la-ne': source-mt
'lt-ne': source-mt
'lv-ne': source-mt
'mg-ne': source-mt
'mi-ne': source-mt
'mhr-ne': source-mt
'mk-ne': source-mt
'mn-ne': source-mt
'mr-ne': source-mt
'mrj-ne': source-mt
'ms-ne': source-mt
'mt-ne': source-mt
'nb-ne': source-mt
'pa-ne': source-mt
'pl-ne': source-mt
'pt-ne': source-mt
'ro-ne': source-mt
'ru-ne': source-mt
'si-ne': source-mt
'sk-ne': source-mt
'sl-ne': source-mt
'sq-ne': source-mt
'sr-ne': source-mt
'su-ne': source-mt
'sv-ne': source-mt
'sw-ne': source-mt
'ta-ne': source-mt
'te-ne': source-mt
'tg-ne': source-mt
'th-ne': source-mt
'tl-ne': source-mt
'tr-ne': source-mt
'tt-ne': source-mt
'udm-ne': source-mt
'uk-ne': source-mt
'ur-ne': source-mt
'uz-ne': source-mt
'vi-ne': source-mt
'xh-ne': source-mt
'yi-ne': source-mt
'zh-ne': source-mt
'am-nl': source-mt
'ar-nl': source-mt
'az-nl': source-mt
'ba-nl': source-mt
'be-nl': source-mt
'bn-nl': source-mt
'bg-nl': source-mt
'bs-nl': source-mt
'ca-nl': source-mt
'ceb-nl': source-mt
'cs-nl': source-mt
'cy-nl': source-mt
'da-nl': source-mt
'de-nl': source-mt
'el-nl': source-mt
'en-nl': source-mt
'eo-nl': source-mt
'es-nl': source-mt
'et-nl': source-mt
'eu-nl': source-mt
'fa-nl': source-mt
'fi-nl': source-mt
'fr-nl': source-mt
'ga-nl': source-mt
'gd-nl': source-mt
'gl-nl': source-mt
'gu-nl': source-mt
'he-nl': source-mt
'hi-nl': source-mt
'hr-nl': source-mt
'ht-nl': source-mt
'hu-nl': source-mt
'hy-nl': source-mt
'id-nl': source-mt
'is-nl': source-mt
'ja-nl': source-mt
'jv-nl': source-mt
'ka-nl': source-mt
'kk-nl': source-mt
'km-nl': source-mt
'kn-nl': source-mt
'ko-nl': source-mt
'ky-nl': source-mt
'la-nl': source-mt
'lb-nl': source-mt
'lo-nl': source-mt
'lt-nl': source-mt
'lv-nl': source-mt
'mg-nl': source-mt
'mi-nl': source-mt
'mhr-nl': source-mt
'ml-nl': source-mt
'mk-nl': source-mt
'mn-nl': source-mt
'mrj-nl': source-mt
'mr-nl': source-mt
'ms-nl': source-mt
'mt-nl': source-mt
'nb-nl': source-mt
'ne-nl': source-mt
'pap-nl': source-mt
'pa-nl': source-mt
'pl-nl': source-mt
'pt-nl': source-mt
'ro-nl': source-mt
'ru-nl': source-mt
'si-nl': source-mt
'sk-nl': source-mt
'sl-nl': source-mt
'sq-nl': source-mt
'sr-nl': source-mt
'su-nl': source-mt
'sv-nl': source-mt
'sw-nl': source-mt
'ta-nl': source-mt
'te-nl': source-mt
'tg-nl': source-mt
'th-nl': source-mt
'tl-nl': source-mt
'tr-nl': source-mt
'tt-nl': source-mt
'udm-nl': source-mt
'uk-nl': source-mt
'ur-nl': source-mt
'uz-nl': source-mt
'vi-nl': source-mt
'xh-nl': source-mt
'yi-nl': source-mt
'zh-nl': source-mt
'en-pa': source-mt
'hi-pa': source-mt
'ru-pa': source-mt
'en-si': source-mt
'ar-sv': source-mt
'da-sv': source-mt
'de-sv': source-mt
'en-sv': source-mt
'es-sv': source-mt
'fi-sv': source-mt
'fr-sv': source-mt
'ja-sv': source-mt
'nl-sv': source-mt
'nb-sv': source-mt
'ru-sv': source-mt
'en-ta': source-mt
'af-te': source-mt
'am-te': source-mt
'ar-te': source-mt
'ba-te': source-mt
'be-te': source-mt
'bn-te': source-mt
'bg-te': source-mt
'bs-te': source-mt
'ca-te': source-mt
'ceb-te': source-mt
'cs-te': source-mt
'cy-te': source-mt
'da-te': source-mt
'el-te': source-mt
'en-te': source-mt
'eo-te': source-mt
'es-te': source-mt
'et-te': source-mt
'eu-te': source-mt
'fa-te': source-mt
'fi-te': source-mt
'fr-te': source-mt
'ga-te': source-mt
'gd-te': source-mt
'gl-te': source-mt
'gu-te': source-mt
'he-te': source-mt
'hi-te': source-mt
'hr-te': source-mt
'ht-te': source-mt
'hu-te': source-mt
'hy-te': source-mt
'id-te': source-mt
'is-te': source-mt
'ja-te': source-mt
'ka-te': source-mt
'kk-te': source-mt
'kn-te': source-mt
'ko-te': source-mt
'ky-te': source-mt
'la-te': source-mt
'lt-te': source-mt
'lv-te': source-mt
'mg-te': source-mt
'mi-te': source-mt
'mhr-te': source-mt
'mk-te': source-mt
'mn-te': source-mt
'mr-te': source-mt
'mrj-te': source-mt
'ms-te': source-mt
'mt-te': source-mt
'nb-te': source-mt
'ne-te': source-mt
'pa-te': source-mt
'pl-te': source-mt
'pt-te': source-mt
'ro-te': source-mt
'ru-te': source-mt
'si-te': source-mt
'sk-te': source-mt
'sl-te': source-mt
'sq-te': source-mt
'sr-te': source-mt
'su-te': source-mt
'sv-te': source-mt
'sw-te': source-mt
'ta-te': source-mt
'tg-te': source-mt
'th-te': source-mt
'tl-te': source-mt
'tr-te': source-mt
'tt-te': source-mt
'udm-te': source-mt
'uk-te': source-mt
'ur-te': source-mt
'uz-te': source-mt
'vi-te': source-mt
'yi-te': source-mt
'xh-te': source-mt
'be-uk': source-mt
'cs-uk': source-mt
'de-uk': source-mt
'en-uk': source-mt
'es-uk': source-mt
'et-uk': source-mt
'fr-uk': source-mt
'it-uk': source-mt
'ja-uk': source-mt
'nl-uk': source-mt
'pl-uk': source-mt
'ro-uk': source-mt
'ru-uk': source-mt
'sk-uk': source-mt
'sv-uk': source-mt
'en-yi': source-mt
'he-yi': source-mt
'af-zh': Yandex
'am-zh': Yandex
'ar-zh': Yandex
'az-zh': Yandex
'ba-zh': Yandex
'be-zh': Yandex
'be-tarask-zh': Yandex
'bn-zh': Yandex
'bg-zh': Yandex
'bs-zh': Yandex
'ca-zh': Yandex
'ceb-zh': Yandex
'cs-zh': Yandex
'cy-zh': Yandex
'da-zh': Yandex
'el-zh': Yandex
'en-zh': Yandex
'eo-zh': Yandex
'es-zh': Yandex
'et-zh': Yandex
'eu-zh': Yandex
'fa-zh': Yandex
'fi-zh': Yandex
'fr-zh': Yandex
'ga-zh': Yandex
'gd-zh': Yandex
'gl-zh': Yandex
'gu-zh': Yandex
'he-zh': Yandex
'hi-zh': Yandex
'hr-zh': Yandex
'ht-zh': Yandex
'hu-zh': Yandex
'hy-zh': Yandex
'id-zh': Yandex
'is-zh': Yandex
'ja-zh': Yandex
'ka-zh': Yandex
'kk-zh': Yandex
'kn-zh': Yandex
'ko-zh': Yandex
'ky-zh': Yandex
'la-zh': Yandex
'lt-zh': Yandex
'lv-zh': Yandex
'mg-zh': Yandex
'mi-zh': Yandex
'mhr-zh': Yandex
'mk-zh': Yandex
'mn-zh': Yandex
'mr-zh': Yandex
'mrj-zh': Yandex
'ms-zh': Yandex
'mt-zh': Yandex
'nb-zh': Yandex
'ne-zh': Yandex
'pa-zh': Yandex
'pl-zh': Yandex
'pt-zh': Yandex
'ro-zh': Yandex
'ru-zh': Yandex
'si-zh': Yandex
'sk-zh': Yandex
'sl-zh': Yandex
'sq-zh': Yandex
'sr-zh': Yandex
'su-zh': Yandex
'sv-zh': Yandex
'sw-zh': Yandex
'ta-zh': Yandex
'te-zh': Yandex
'tg-zh': Yandex
'th-zh': Yandex
'tl-zh': Yandex
'tr-zh': Yandex
'tt-zh': Yandex
'udm-zh': Yandex
'uk-zh': Yandex
'ur-zh': Yandex
'uz-zh': Yandex
'vi-zh': Yandex
'yi-zh': Yandex
'xh-zh': Yandex
'nl-af': Apertium
'mt-ar': Apertium
'ru-be': Apertium
'mk-bg': Apertium
'en-ca': Apertium
'es-ca': Apertium
'fr-ca': Apertium
'it-ca': Apertium
'pt-ca': Apertium
'sv-da': Apertium
'ca-es': Apertium
'en-es': Apertium
'eu-es': Apertium
'fr-es': Apertium
'gl-es': Apertium
'it-es': Apertium
'pt-es': Apertium
'ro-es': Apertium
'ca-fr': Apertium
'es-fr': Apertium
'en-gl': Apertium
'es-gl': Apertium
'pt-gl': Apertium
'ur-hi': Apertium
'ms-id': Apertium
'es-it': Apertium
'sv-is': Apertium
'tt-kk': Apertium
'bg-mk': Apertium
'id-ms': Apertium
'ar-mt': Apertium
'af-nl': Apertium
'ca-pt': Apertium
'es-pt': Apertium
'gl-pt': Apertium
'be-ru': Apertium
'ca-sc': Apertium
'it-sc': Apertium
'sh-sl': Apertium
'mk-sr': Apertium
'sl-sr': Apertium
'is-sv': Apertium
'kk-tt': Apertium
'hi-ur': Apertium
