handler: Yandex.js
notAsTarget:
  - be-tarask
  - de
  - en
  - it
languages:
  - af
  - am
  - ar
  - az
  - ba
  - be
  - be-tarask
  - bn
  - bg
  - bs
  - ca
  - ceb
  - cs
  - cy
  - da
  - de
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fa
  - fi
  - fr
  - ga
  - gd
  - gl
  - gu
  - he
  - hi
  - hr
  - ht
  - hu
  - hy
  - id
  - is
  - it
  - ja
  - jv
  - ka
  - kk
  - km
  - kn
  - ko
  - ky
  - la
  - lb
  - lo
  - lt
  - lv
  - mi
  - mg
  - mhr
  - ml
  - mk
  - mn
  - mrj
  - mr
  - ms
  - mt
  - my
  - nb
  - ne
  - nl
  - pa
  - pap
  - pl
  - pt
  - ro
  - ru
  - si
  - sk
  - sl
  - sq
  - sr
  - su
  - sv
  - sw
  - ta
  - te
  - tg
  - th
  - tl
  - tr
  - tt
  - udm
  - uk
  - ur
  - uz
  - vi
  - xh
  - yi
  - zh
